{
 "title": "Cluster Overview",
 "tags": [
  "EMR",
  "Costs"
 ],
 "time": { "from": "2023-07-10T12:19:55.600Z", "to": "2023-07-10T14:13:14.062Z" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-central-1,eu-central-2,eu-west-1,eu-west-2,eu-west-3,eu-south-1,eu-south-2,eu-north-1,af-south-1,ap-east-1,ap-south-1,ap-south-2,ap-northeast-1,ap-northeast-2,ap-northeast-3,ap-southeast-1,ap-southeast-2,ap-southeast-3,ap-southeast-4,ca-central-1,me-south-1,me-central-1,sa-east-1,il-central-1"
   },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster_id)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{cluster_id=~'$cluster'},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cost Breakdown",
   "type": "piechart",
   "description": "The cost of a particular cluster is the sum of individual cost estimations of its instances, the logic supports on-demand and spot prices.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "payload": { "cluster_id": "$cluster", "region": "$region" }, "target": "Breakdown" }
   ]
  },
  {
   "title": "Active cluster nodes for $cluster",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up {job='node_scraper', cluster_id=~'$cluster', instance=~\"$instance\"}",
     "legendFormat": "{{instance}} ({{cluster_id}})"
    }
   ]
  },
  {
   "title": "Spark apps on $cluster",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "last_over_time(spark_jvmCpuTime{cluster_id=~\"$cluster\", agent=\"driver\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "tfirst_over_time(spark_jvmCpuTime{cluster_id=~\"$cluster\", agent=\"driver\"}[$__range]) * 1000",
     "legendFormat": "Min"
    },
    {
     "expr": "tlast_over_time(spark_jvmCpuTime{cluster_id=~\"$cluster\", agent=\"driver\"}[$__range])  * 1000",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Instances of $cluster",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 12 },
   "targets": [
    { "payload": { "cluster_id": "$cluster", "region": "$region" }, "target": "InstanceList" }
   ]
  },
  {
   "title": "Cluster Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Nodes Up",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up {job='node_scraper', cluster_id=~'$cluster', instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count(node_cpu_seconds_total{job='node_scraper', cluster_id=~'$cluster', instance=~\"$instance\", mode='system'}) by (cpu))"
      }
     ]
    },
    {
     "title": "Normalized System Load",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_load1 {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)/count(node_cpu_seconds_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode='system'}) by (cluster_id, instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "Size"
      },
      {
       "expr": "node_filesystem_avail_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}-0",
       "legendFormat": "Available"
      },
      {
       "expr": "1- (node_filesystem_avail_bytes{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} / node_filesystem_size_bytes{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job='node_scraper', cluster_id=~'$cluster',  instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Total Disks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~\"$instance\", fstype!=\"tmpfs\", mountpoint !~ \".*tmp.*\"})"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by (cluster_id, instance) (irate(node_cpu_seconds_total{job='node_scraper', cluster_id=~'$cluster', instance=~\"$instance\", mode=\"idle\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-(sum(node_memory_MemAvailable_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)) / (sum(node_memory_MemTotal_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Paging",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]) + rate(node_vmstat_pswpout {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_weighted_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Transmission Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Network Receive Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by (cluster_id, instance) (irate(node_cpu_seconds_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode=\"idle\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Utilization Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 16, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (mode, cluster_id, instance) (irate(node_cpu_seconds_total{job='node_scraper',cluster_id=~'$cluster', instance=~'$instance', mode != \"idle\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{mode}}"
      }
     ]
    },
    {
     "title": "System Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode=\"system\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "User Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode=\"user\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Idle Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode=\"idle\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IOWait Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode=\"iowait\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Steal Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode=\"steal\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IRQ Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster',instance=~'$instance', mode=\"irq\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper',  cluster_id=~'$cluster',instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NICE Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper',  cluster_id=~'$cluster',instance=~'$instance', mode=\"nice\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster',instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Soft IRQ Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance', mode=\"softirq\"} [$__rate_interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Normalized System Load",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_load1 {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)/count(node_cpu_seconds_total{job='node_scraper',  cluster_id=~'$cluster', instance=~'$instance', mode='system'}) by (cluster_id, instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_weighted_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_written_bytes_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_read_bytes_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Merged Write I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_writes_merged_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Merged Read I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_reads_merged_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk I/O Request Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": " ((sum by (job, cluster_id, instance)(rate(node_disk_read_bytes_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])))+(sum by (job, cluster_id, instance)(rate(node_disk_written_bytes_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval]))))/((sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval]))) + (sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval]))))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Write Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (job, cluster_id, instance)(rate(node_disk_write_time_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval])))/(sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Read Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (job, cluster_id, instance)(rate(node_disk_read_time_seconds_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval])))/(sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-(sum(node_memory_MemAvailable_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)) / (sum(node_memory_MemTotal_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Paging",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]) + rate(node_vmstat_pswpout {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Swap Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-node_memory_SwapFree_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} / node_memory_SwapTotal_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Commit Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes {job='node_scraper', cluster_id=~'$cluster',instance=~'$instance'}/node_memory_CommitLimit_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OOM Kill",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": " rate(node_vmstat_oom_kill{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network I/O Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Up",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_network_up {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Network Transmission Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Network Receive Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Transmission Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_packets_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Receive Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Transmission Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_errs_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])/rate(node_network_transmit_packets_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Receive Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])/rate(node_network_transmit_packets_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Transmission Drop",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_drop_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])/rate(node_network_transmit_packets_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Receive Drop",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])/rate(node_network_transmit_packets_total{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File System Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "Size"
      },
      {
       "expr": "node_filesystem_avail_bytes {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}-0",
       "legendFormat": "Available"
      },
      {
       "expr": "1- (node_filesystem_avail_bytes{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} / node_filesystem_size_bytes{job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_open_fds {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}/ process_max_fds {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File System Device Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_filesystem_device_error {job='node_scraper', cluster_id=~'$cluster', instance=~'$instance'} [$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}