{
 "title": "General Overview",
 "tags": [
  "EMR",
  "Costs"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": "us-east-1,us-east-2,us-west-1,us-west-2,eu-central-1,eu-central-2,eu-west-1,eu-west-2,eu-west-3,eu-south-1,eu-south-2,eu-north-1,af-south-1,ap-east-1,ap-south-1,ap-south-2,ap-northeast-1,ap-northeast-2,ap-northeast-3,ap-southeast-1,ap-southeast-2,ap-southeast-3,ap-southeast-4,ca-central-1,me-south-1,me-central-1,sa-east-1,il-central-1"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Cluster Resources",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\"region\": \"$region\"}",
     "target": "ActiveResources"
    }
   ]
  },
  {
   "title": "Total Tracked Cluster Costs",
   "type": "piechart",
   "description": "Total costs of clusters that were tracked and on which Spark apps ran. The cost of a particular cluster is the sum of individual cost estimations of its instances, the logic supports on-demand and spot prices.",
   "gridPos": { "h": 11, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\n  \"region\": \"$region\"\n}",
     "target": "ComputeCosts"
    }
   ]
  },
  {
   "title": "Tracked Clusters Utilisation",
   "type": "gauge",
   "description": "Average CPU utilization of tracked clusters on which Spark apps ran.",
   "gridPos": { "h": 11, "w": 9, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\n  \"region\": \"$region\"\n}",
     "target": "ComputeUtil"
    }
   ]
  },
  {
   "title": "Spark Apps in $region",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "payload": "{\"region\": \"$region\"}",
     "target": "AppList"
    }
   ]
  }
 ]
}