apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    editable: true
    isDefault: true
    uid: prometheusdatasource
    jsonData:
      timeInterval: 10s
