global:
  scrape_interval: 10s
scrape_configs:
  - job_name: node_scraper
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
        job: 'node_scraper'
        cluster_id: 'local'
        instance: 'local'
