{
 "title": "Spark Info",
 "tags": [ "Databricks" ],
 "time": { "from": "2024-03-11T16:25:22.000Z", "to": "2024-03-11T16:41:32.000Z" },
 "templating": {
  "list": [
   { "name": "appid", "label": "App", "query": { "query": "label_values(app_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Active Tasks Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(spark_threadpool_activeTasks{app_id=\"$appid\"})",
     "legendFormat": "Active Tasks Total"
    }
   ]
  },
  { "title": "Application Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Application Start",
   "type": "stat",
   "description": "Approximate application start based on the first CPU data point of the driver.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "tfirst_over_time(spark_jvmCpuTime{app_id=\"$appid\", agent=\"driver\"}[$__range]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application End",
   "type": "stat",
   "description": "Approximate application end based on the last CPU data point of the driver.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tlast_over_time(spark_jvmCpuTime{app_id=\"$appid\", agent=\"driver\"}[$__range]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_jobs_succeededJobs_count{app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succeeded Tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_succeededTasks_count{app_id=\"$appid\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Completed Stages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_stages_completedStages_count{app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_bytesRead_count{app_id=\"$appid\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Written",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_bytesWritten_count{app_id=\"$appid\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_jobs_failedJobs_count{app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_tasks_skippedTasks_count{app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Stages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_stages_skippedStages_count{app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Read",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_recordsRead_count{app_id=\"$appid\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Written",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_recordsWritten_count{app_id=\"$appid\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_tasks_failedTasks_count{app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_stages_failedStages_count{app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Task Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_runTime_count{app_id=\"$appid\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task JVM CPU Time",
   "type": "stat",
   "description": "JVM Process CPU time, subsumes all JVM CPU activities like garbage collection, tasks CPU, ...",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_jvmCpuTime{agent != \"driver\", app_id=\"$appid\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task CPU Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_cpuTime_count{app_id=\"$appid\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors GC Time",
   "type": "stat",
   "description": "Time spent on garbage collection on the executors ",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_jvmGCTime_count{app_id=\"$appid\", agent != \"driver\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver JVM CPU Time",
   "type": "stat",
   "description": "JVM Process CPU time for the driver, subsumes all JVM CPU activities like garbage collection, driver CPU, ...",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(spark_jvmCpuTime{agent=\"driver\", app_id=\"$appid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver GC Time",
   "type": "stat",
   "description": "Time spent on garbage collection on the driver ",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(spark_MajorGCTime{app_id=\"$appid\", agent = \"driver\"}[$__range])) + sum(last_over_time(spark_MinorGCTime{app_id=\"$appid\", agent = \"driver\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Metrics (Container & JVM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Resident Memory Usage",
     "type": "timeseries",
     "description": "Physical memory allocated & used",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_ProcessTreeJVMRSSMemory{app_id = \"$appid\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Executors Usage per Memory Areas",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(spark_ProcessTreeJVMRSSMemory{app_id = \"$appid\", agent != \"driver\"})",
       "legendFormat": "Total Memory Used"
      },
      {
       "expr": "sum(spark_JVMHeapMemory{app_id = \"$appid\", agent != \"driver\"}) ",
       "legendFormat": "JVM Heap"
      },
      {
       "expr": "sum(spark_JVMOffHeapMemory{app_id = \"$appid\", agent != \"driver\"}) ",
       "legendFormat": "JVM OffHeap"
      },
      {
       "expr": "sum(spark_ProcessTreePythonRSSMemory{app_id = \"$appid\", agent != \"driver\"}) ",
       "legendFormat": "PySpark"
      },
      {
       "expr": "sum(spark_ProcessTreeOtherRSSMemory{app_id = \"$appid\", agent != \"driver\"})  ",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Driver JVM Memory Sizes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_heap_used{app_id = \"$appid\", agent = \"driver\"}",
       "legendFormat": "{{__name__}} (Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_heap_committed{app_id = \"$appid\", agent = \"driver\"}",
       "legendFormat": "{{__name__}} (Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_heap_max{app_id = \"$appid\", agent = \"driver\"}",
       "legendFormat": "{{__name__}} (Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Executors JVM Memory Sizes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_heap_used{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_heap_committed{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_heap_max{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Driver Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_JVMHeapMemory{app_id = \"$appid\", agent = \"driver\"}",
       "legendFormat": "{{__name__}} (Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Executors Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_JVMHeapMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Executors Heap Memory Compartments",
     "type": "timeseries",
     "description": "Shows memory usage per Spark memory compartment. See  https://g1thubhub.github.io/spark-memory.html for details.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_OnHeapUnifiedMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_OnHeapExecutionMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_OnHeapStorageMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Driver OffHeap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_JVMOffHeapMemory{app_id = \"$appid\", agent = \"driver\"}",
       "legendFormat": "{{__name__}} (Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Executors OffHeap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_JVMOffHeapMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Executor OffHeap Memory Compartments",
     "type": "timeseries",
     "description": "Shows memory usage per Spark memory compartment. See  https://g1thubhub.github.io/spark-memory.html for details",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_OffHeapUnifiedMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_OffHeapExecutionMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      },
      {
       "expr": "spark_OffHeapStorageMemory{app_id = \"$appid\", agent != \"driver\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Executors CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "avg by (agent) (deriv(spark_jvmCpuTime{agent != \"driver\", app_id=\"$appid\"}[$__rate_interval]))  / 1000000000 ",
       "legendFormat": "JVM CPUTime Exec {{agent}}"
      },
      {
       "expr": "avg by (agent) (rate(spark_cpuTime_count{app_id=\"$appid\"}[$__rate_interval])) / 1000000000 ",
       "legendFormat": "Task CPUTime Exec {{agent}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Metrics (Python & Other)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python RSS",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_ProcessTreePythonRSSMemory{app_id = \"$appid\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Python Virtual Memory Size",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_ProcessTreePythonVMemory{app_id = \"$appid\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Other RSS",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_ProcessTreeOtherRSSMemory{app_id = \"$appid\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    },
    {
     "title": "Other Virtual Memory Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spark_ProcessTreeOtherVMemory{app_id = \"$appid\"}",
       "legendFormat": "{{__name__}} (Exec {{agent}}, Cluster {{cluster_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Time Components",
     "type": "barchart",
     "description": "Proportion of time spent on different executor activities. Spark's metric system does not expose IO metrics so the individual components may not always add up to 1.0. A custom SparkListener would be required for measuring Scan Time for example",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(spark_deserializeTime_count{app_id=\"$appid\"}))/ sum(spark_runTime_count{app_id=\"$appid\"})",
       "legendFormat": "DeserTime"
      },
      {
       "expr": "(sum(spark_cpuTime_count{app_id=\"$appid\"}) / 1000000) / sum(spark_runTime_count{app_id=\"$appid\"})",
       "legendFormat": "CpuTime"
      },
      {
       "expr": "(sum(spark_shuffleWriteTime_count{app_id=\"$appid\"}) / 1000000)  / sum(spark_runTime_count{app_id=\"$appid\"})",
       "legendFormat": "ShuffleWriteTime"
      },
      {
       "expr": "sum(spark_resultSerializationTime_count{app_id=\"$appid\"})  / sum(spark_runTime_count{app_id=\"$appid\"})",
       "legendFormat": "resultSerializationTime"
      },
      {
       "expr": "sum(spark_shuffleFetchWaitTime_count{app_id=\"$appid\"}) / sum(spark_runTime_count{app_id=\"$appid\"})",
       "legendFormat": "ShuffleFetchWaitTime"
      },
      {
       "expr": "sum(spark_jvmGCTime_count{app_id=\"$appid\"})  / sum(spark_runTime_count{app_id=\"$appid\"})",
       "legendFormat": "GCTime"
      }
     ]
    },
    {
     "title": "Executor Time Components Rate",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(max(rate(spark_deserializeTime_count{app_id=\"$appid\"}[$__rate_interval])) by (agent) / 1000)",
       "legendFormat": "Deser Time"
      },
      {
       "expr": "sum(max(rate(spark_cpuTime_count{app_id=\"$appid\"}[$__rate_interval])) by (agent) / 1000000000)",
       "legendFormat": "CPU Time"
      },
      {
       "expr": "sum(max(rate(spark_shuffleWriteTime_count{app_id=\"$appid\"}[$__rate_interval])) by (agent) / 1000000000 )",
       "legendFormat": "ShuffleWriteTime"
      },
      {
       "expr": "sum(max(rate(spark_resultSerializationTime_count{app_id=\"$appid\"}[$__rate_interval])) by (agent) / 1000 )",
       "legendFormat": "Result Ser Time"
      },
      {
       "expr": "sum(max(rate(spark_shuffleFetchWaitTime_count{app_id=\"$appid\"}[$__rate_interval])) by (agent) / 1000 )",
       "legendFormat": "Shuffle F Wait Time"
      },
      {
       "expr": "sum(max(rate(spark_jvmGCTime_count{app_id=\"$appid\"}[$__rate_interval])) by (agent) / 1000 )",
       "legendFormat": "GC Time"
      },
      {
       "expr": "sum(max(rate(spark_runTime_count{app_id=\"$appid\"}[$__rate_interval])) by (agent) / 1000)",
       "legendFormat": "Run Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Major GC Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_MajorGCCount{app_id = \"$appid\"}[$__range]))",
       "legendFormat": "Executor {{agent}}"
      }
     ]
    },
    {
     "title": "Total Minor GC Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 11, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_MinorGCCount{app_id = \"$appid\"}[$__range]))",
       "legendFormat": "Executor {{agent}}"
      }
     ]
    },
    {
     "title": "Major GC Count Distribution",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "spark_MajorGCCount{app_id = \"$appid\"}[$__range]",
       "legendFormat": "Exec {{agent}}"
      }
     ]
    },
    {
     "title": "Minor GC Count Distribution",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "spark_MinorGCCount{app_id = \"$appid\"}[$__range]",
       "legendFormat": "Exec {{agent}}"
      }
     ]
    },
    {
     "title": "Major GC Time Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "deriv(spark_MajorGCTime{app_id = \"$appid\"}[$__rate_interval])",
       "legendFormat": "Executor {{agent}}"
      }
     ]
    },
    {
     "title": "Minor GC Time Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "deriv(spark_MinorGCTime{app_id = \"$appid\"}[$__rate_interval])",
       "legendFormat": "Executor {{agent}}"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shuffle Bytes Read",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_shuffleTotalBytesRead_count{app_id=\"$appid\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shuffle Bytes Written",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_shuffleBytesWritten_count{app_id=\"$appid\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Spill Size (Disk)",
     "type": "stat",
     "description": "The size of the serialized form of the shuffled data on disk",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_diskBytesSpilled_count{app_id=\"$appid\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Spill Size (Memory)",
     "type": "stat",
     "description": "The size of the deserialized form of the shuffled data in memory",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_memoryBytesSpilled_count{app_id=\"$appid\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Spill Rate (Memory)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(spark_memoryBytesSpilled_count{app_id=\"$appid\"}[$__rate_interval])",
       "legendFormat": "Exec {{agent}}"
      }
     ]
    },
    {
     "title": "Shuffle Fetch Wait Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_shuffleFetchWaitTime_count{app_id=\"$appid\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Shuffle Write Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(spark_shuffleWriteTime_count{app_id=\"$appid\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shuffle Fetch Wait Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(spark_shuffleFetchWaitTime_count{app_id=\"$appid\"}[$__rate_interval]) / 1000",
       "legendFormat": "Exec {{agent}}"
      }
     ]
    }
   ]
  }
 ]
}